export const API_V1_BUSINESSPHOTO_LIST = "API_V1_BUSINESSPHOTO_LIST"
export const API_V1_BUSINESSPHOTO_LIST_SUCCEEDED =
  "API_V1_BUSINESSPHOTO_LIST_SUCCEEDED"
export const API_V1_BUSINESSPHOTO_LIST_FAILED =
  "API_V1_BUSINESSPHOTO_LIST_FAILED"
export const API_V1_BUSINESSPHOTO_CREATE = "API_V1_BUSINESSPHOTO_CREATE"
export const API_V1_BUSINESSPHOTO_CREATE_SUCCEEDED =
  "API_V1_BUSINESSPHOTO_CREATE_SUCCEEDED"
export const API_V1_BUSINESSPHOTO_CREATE_FAILED =
  "API_V1_BUSINESSPHOTO_CREATE_FAILED"
export const API_V1_BUSINESSPHOTO_READ = "API_V1_BUSINESSPHOTO_READ"
export const API_V1_BUSINESSPHOTO_READ_SUCCEEDED =
  "API_V1_BUSINESSPHOTO_READ_SUCCEEDED"
export const API_V1_BUSINESSPHOTO_READ_FAILED =
  "API_V1_BUSINESSPHOTO_READ_FAILED"
export const API_V1_BUSINESSPHOTO_UPDATE = "API_V1_BUSINESSPHOTO_UPDATE"
export const API_V1_BUSINESSPHOTO_UPDATE_SUCCEEDED =
  "API_V1_BUSINESSPHOTO_UPDATE_SUCCEEDED"
export const API_V1_BUSINESSPHOTO_UPDATE_FAILED =
  "API_V1_BUSINESSPHOTO_UPDATE_FAILED"
export const API_V1_BUSINESSPHOTO_PARTIAL_UPDATE =
  "API_V1_BUSINESSPHOTO_PARTIAL_UPDATE"
export const API_V1_BUSINESSPHOTO_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_BUSINESSPHOTO_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_BUSINESSPHOTO_PARTIAL_UPDATE_FAILED =
  "API_V1_BUSINESSPHOTO_PARTIAL_UPDATE_FAILED"
export const API_V1_BUSINESSPHOTO_DELETE = "API_V1_BUSINESSPHOTO_DELETE"
export const API_V1_BUSINESSPHOTO_DELETE_SUCCEEDED =
  "API_V1_BUSINESSPHOTO_DELETE_SUCCEEDED"
export const API_V1_BUSINESSPHOTO_DELETE_FAILED =
  "API_V1_BUSINESSPHOTO_DELETE_FAILED"
export const API_V1_CATEGORY_LIST = "API_V1_CATEGORY_LIST"
export const API_V1_CATEGORY_LIST_SUCCEEDED = "API_V1_CATEGORY_LIST_SUCCEEDED"
export const API_V1_CATEGORY_LIST_FAILED = "API_V1_CATEGORY_LIST_FAILED"
export const API_V1_CATEGORY_CREATE = "API_V1_CATEGORY_CREATE"
export const API_V1_CATEGORY_CREATE_SUCCEEDED =
  "API_V1_CATEGORY_CREATE_SUCCEEDED"
export const API_V1_CATEGORY_CREATE_FAILED = "API_V1_CATEGORY_CREATE_FAILED"
export const API_V1_CATEGORY_READ = "API_V1_CATEGORY_READ"
export const API_V1_CATEGORY_READ_SUCCEEDED = "API_V1_CATEGORY_READ_SUCCEEDED"
export const API_V1_CATEGORY_READ_FAILED = "API_V1_CATEGORY_READ_FAILED"
export const API_V1_CATEGORY_UPDATE = "API_V1_CATEGORY_UPDATE"
export const API_V1_CATEGORY_UPDATE_SUCCEEDED =
  "API_V1_CATEGORY_UPDATE_SUCCEEDED"
export const API_V1_CATEGORY_UPDATE_FAILED = "API_V1_CATEGORY_UPDATE_FAILED"
export const API_V1_CATEGORY_PARTIAL_UPDATE = "API_V1_CATEGORY_PARTIAL_UPDATE"
export const API_V1_CATEGORY_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CATEGORY_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CATEGORY_PARTIAL_UPDATE_FAILED =
  "API_V1_CATEGORY_PARTIAL_UPDATE_FAILED"
export const API_V1_CATEGORY_DELETE = "API_V1_CATEGORY_DELETE"
export const API_V1_CATEGORY_DELETE_SUCCEEDED =
  "API_V1_CATEGORY_DELETE_SUCCEEDED"
export const API_V1_CATEGORY_DELETE_FAILED = "API_V1_CATEGORY_DELETE_FAILED"
export const API_V1_CUSTOMERLOCATION_LIST = "API_V1_CUSTOMERLOCATION_LIST"
export const API_V1_CUSTOMERLOCATION_LIST_SUCCEEDED =
  "API_V1_CUSTOMERLOCATION_LIST_SUCCEEDED"
export const API_V1_CUSTOMERLOCATION_LIST_FAILED =
  "API_V1_CUSTOMERLOCATION_LIST_FAILED"
export const API_V1_CUSTOMERLOCATION_CREATE = "API_V1_CUSTOMERLOCATION_CREATE"
export const API_V1_CUSTOMERLOCATION_CREATE_SUCCEEDED =
  "API_V1_CUSTOMERLOCATION_CREATE_SUCCEEDED"
export const API_V1_CUSTOMERLOCATION_CREATE_FAILED =
  "API_V1_CUSTOMERLOCATION_CREATE_FAILED"
export const API_V1_CUSTOMERLOCATION_READ = "API_V1_CUSTOMERLOCATION_READ"
export const API_V1_CUSTOMERLOCATION_READ_SUCCEEDED =
  "API_V1_CUSTOMERLOCATION_READ_SUCCEEDED"
export const API_V1_CUSTOMERLOCATION_READ_FAILED =
  "API_V1_CUSTOMERLOCATION_READ_FAILED"
export const API_V1_CUSTOMERLOCATION_UPDATE = "API_V1_CUSTOMERLOCATION_UPDATE"
export const API_V1_CUSTOMERLOCATION_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMERLOCATION_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMERLOCATION_UPDATE_FAILED =
  "API_V1_CUSTOMERLOCATION_UPDATE_FAILED"
export const API_V1_CUSTOMERLOCATION_PARTIAL_UPDATE =
  "API_V1_CUSTOMERLOCATION_PARTIAL_UPDATE"
export const API_V1_CUSTOMERLOCATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMERLOCATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMERLOCATION_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMERLOCATION_PARTIAL_UPDATE_FAILED"
export const API_V1_CUSTOMERLOCATION_DELETE = "API_V1_CUSTOMERLOCATION_DELETE"
export const API_V1_CUSTOMERLOCATION_DELETE_SUCCEEDED =
  "API_V1_CUSTOMERLOCATION_DELETE_SUCCEEDED"
export const API_V1_CUSTOMERLOCATION_DELETE_FAILED =
  "API_V1_CUSTOMERLOCATION_DELETE_FAILED"
export const API_V1_CUSTOMERPROFILE_LIST = "API_V1_CUSTOMERPROFILE_LIST"
export const API_V1_CUSTOMERPROFILE_LIST_SUCCEEDED =
  "API_V1_CUSTOMERPROFILE_LIST_SUCCEEDED"
export const API_V1_CUSTOMERPROFILE_LIST_FAILED =
  "API_V1_CUSTOMERPROFILE_LIST_FAILED"
export const API_V1_CUSTOMERPROFILE_CREATE = "API_V1_CUSTOMERPROFILE_CREATE"
export const API_V1_CUSTOMERPROFILE_CREATE_SUCCEEDED =
  "API_V1_CUSTOMERPROFILE_CREATE_SUCCEEDED"
export const API_V1_CUSTOMERPROFILE_CREATE_FAILED =
  "API_V1_CUSTOMERPROFILE_CREATE_FAILED"
export const API_V1_CUSTOMERPROFILE_READ = "API_V1_CUSTOMERPROFILE_READ"
export const API_V1_CUSTOMERPROFILE_READ_SUCCEEDED =
  "API_V1_CUSTOMERPROFILE_READ_SUCCEEDED"
export const API_V1_CUSTOMERPROFILE_READ_FAILED =
  "API_V1_CUSTOMERPROFILE_READ_FAILED"
export const API_V1_CUSTOMERPROFILE_UPDATE = "API_V1_CUSTOMERPROFILE_UPDATE"
export const API_V1_CUSTOMERPROFILE_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMERPROFILE_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMERPROFILE_UPDATE_FAILED =
  "API_V1_CUSTOMERPROFILE_UPDATE_FAILED"
export const API_V1_CUSTOMERPROFILE_PARTIAL_UPDATE =
  "API_V1_CUSTOMERPROFILE_PARTIAL_UPDATE"
export const API_V1_CUSTOMERPROFILE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMERPROFILE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMERPROFILE_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMERPROFILE_PARTIAL_UPDATE_FAILED"
export const API_V1_CUSTOMERPROFILE_DELETE = "API_V1_CUSTOMERPROFILE_DELETE"
export const API_V1_CUSTOMERPROFILE_DELETE_SUCCEEDED =
  "API_V1_CUSTOMERPROFILE_DELETE_SUCCEEDED"
export const API_V1_CUSTOMERPROFILE_DELETE_FAILED =
  "API_V1_CUSTOMERPROFILE_DELETE_FAILED"
export const API_V1_CUSTOMERWALLET_LIST = "API_V1_CUSTOMERWALLET_LIST"
export const API_V1_CUSTOMERWALLET_LIST_SUCCEEDED =
  "API_V1_CUSTOMERWALLET_LIST_SUCCEEDED"
export const API_V1_CUSTOMERWALLET_LIST_FAILED =
  "API_V1_CUSTOMERWALLET_LIST_FAILED"
export const API_V1_CUSTOMERWALLET_CREATE = "API_V1_CUSTOMERWALLET_CREATE"
export const API_V1_CUSTOMERWALLET_CREATE_SUCCEEDED =
  "API_V1_CUSTOMERWALLET_CREATE_SUCCEEDED"
export const API_V1_CUSTOMERWALLET_CREATE_FAILED =
  "API_V1_CUSTOMERWALLET_CREATE_FAILED"
export const API_V1_CUSTOMERWALLET_READ = "API_V1_CUSTOMERWALLET_READ"
export const API_V1_CUSTOMERWALLET_READ_SUCCEEDED =
  "API_V1_CUSTOMERWALLET_READ_SUCCEEDED"
export const API_V1_CUSTOMERWALLET_READ_FAILED =
  "API_V1_CUSTOMERWALLET_READ_FAILED"
export const API_V1_CUSTOMERWALLET_UPDATE = "API_V1_CUSTOMERWALLET_UPDATE"
export const API_V1_CUSTOMERWALLET_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMERWALLET_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMERWALLET_UPDATE_FAILED =
  "API_V1_CUSTOMERWALLET_UPDATE_FAILED"
export const API_V1_CUSTOMERWALLET_PARTIAL_UPDATE =
  "API_V1_CUSTOMERWALLET_PARTIAL_UPDATE"
export const API_V1_CUSTOMERWALLET_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMERWALLET_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMERWALLET_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMERWALLET_PARTIAL_UPDATE_FAILED"
export const API_V1_CUSTOMERWALLET_DELETE = "API_V1_CUSTOMERWALLET_DELETE"
export const API_V1_CUSTOMERWALLET_DELETE_SUCCEEDED =
  "API_V1_CUSTOMERWALLET_DELETE_SUCCEEDED"
export const API_V1_CUSTOMERWALLET_DELETE_FAILED =
  "API_V1_CUSTOMERWALLET_DELETE_FAILED"
export const API_V1_CUSTOMTEXT_LIST = "API_V1_CUSTOMTEXT_LIST"
export const API_V1_CUSTOMTEXT_LIST_SUCCEEDED =
  "API_V1_CUSTOMTEXT_LIST_SUCCEEDED"
export const API_V1_CUSTOMTEXT_LIST_FAILED = "API_V1_CUSTOMTEXT_LIST_FAILED"
export const API_V1_CUSTOMTEXT_READ = "API_V1_CUSTOMTEXT_READ"
export const API_V1_CUSTOMTEXT_READ_SUCCEEDED =
  "API_V1_CUSTOMTEXT_READ_SUCCEEDED"
export const API_V1_CUSTOMTEXT_READ_FAILED = "API_V1_CUSTOMTEXT_READ_FAILED"
export const API_V1_CUSTOMTEXT_UPDATE = "API_V1_CUSTOMTEXT_UPDATE"
export const API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_UPDATE_FAILED = "API_V1_CUSTOMTEXT_UPDATE_FAILED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED"
export const API_V1_HOMEPAGE_LIST = "API_V1_HOMEPAGE_LIST"
export const API_V1_HOMEPAGE_LIST_SUCCEEDED = "API_V1_HOMEPAGE_LIST_SUCCEEDED"
export const API_V1_HOMEPAGE_LIST_FAILED = "API_V1_HOMEPAGE_LIST_FAILED"
export const API_V1_HOMEPAGE_READ = "API_V1_HOMEPAGE_READ"
export const API_V1_HOMEPAGE_READ_SUCCEEDED = "API_V1_HOMEPAGE_READ_SUCCEEDED"
export const API_V1_HOMEPAGE_READ_FAILED = "API_V1_HOMEPAGE_READ_FAILED"
export const API_V1_HOMEPAGE_UPDATE = "API_V1_HOMEPAGE_UPDATE"
export const API_V1_HOMEPAGE_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_UPDATE_FAILED = "API_V1_HOMEPAGE_UPDATE_FAILED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE = "API_V1_HOMEPAGE_PARTIAL_UPDATE"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_INVITECODE_LIST = "API_V1_INVITECODE_LIST"
export const API_V1_INVITECODE_LIST_SUCCEEDED =
  "API_V1_INVITECODE_LIST_SUCCEEDED"
export const API_V1_INVITECODE_LIST_FAILED = "API_V1_INVITECODE_LIST_FAILED"
export const API_V1_INVITECODE_CREATE = "API_V1_INVITECODE_CREATE"
export const API_V1_INVITECODE_CREATE_SUCCEEDED =
  "API_V1_INVITECODE_CREATE_SUCCEEDED"
export const API_V1_INVITECODE_CREATE_FAILED = "API_V1_INVITECODE_CREATE_FAILED"
export const API_V1_INVITECODE_READ = "API_V1_INVITECODE_READ"
export const API_V1_INVITECODE_READ_SUCCEEDED =
  "API_V1_INVITECODE_READ_SUCCEEDED"
export const API_V1_INVITECODE_READ_FAILED = "API_V1_INVITECODE_READ_FAILED"
export const API_V1_INVITECODE_UPDATE = "API_V1_INVITECODE_UPDATE"
export const API_V1_INVITECODE_UPDATE_SUCCEEDED =
  "API_V1_INVITECODE_UPDATE_SUCCEEDED"
export const API_V1_INVITECODE_UPDATE_FAILED = "API_V1_INVITECODE_UPDATE_FAILED"
export const API_V1_INVITECODE_PARTIAL_UPDATE =
  "API_V1_INVITECODE_PARTIAL_UPDATE"
export const API_V1_INVITECODE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_INVITECODE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_INVITECODE_PARTIAL_UPDATE_FAILED =
  "API_V1_INVITECODE_PARTIAL_UPDATE_FAILED"
export const API_V1_INVITECODE_DELETE = "API_V1_INVITECODE_DELETE"
export const API_V1_INVITECODE_DELETE_SUCCEEDED =
  "API_V1_INVITECODE_DELETE_SUCCEEDED"
export const API_V1_INVITECODE_DELETE_FAILED = "API_V1_INVITECODE_DELETE_FAILED"
export const API_V1_LOGIN_CREATE = "API_V1_LOGIN_CREATE"
export const API_V1_LOGIN_CREATE_SUCCEEDED = "API_V1_LOGIN_CREATE_SUCCEEDED"
export const API_V1_LOGIN_CREATE_FAILED = "API_V1_LOGIN_CREATE_FAILED"
export const API_V1_MAPLOCATION_LIST = "API_V1_MAPLOCATION_LIST"
export const API_V1_MAPLOCATION_LIST_SUCCEEDED =
  "API_V1_MAPLOCATION_LIST_SUCCEEDED"
export const API_V1_MAPLOCATION_LIST_FAILED = "API_V1_MAPLOCATION_LIST_FAILED"
export const API_V1_MAPLOCATION_CREATE = "API_V1_MAPLOCATION_CREATE"
export const API_V1_MAPLOCATION_CREATE_SUCCEEDED =
  "API_V1_MAPLOCATION_CREATE_SUCCEEDED"
export const API_V1_MAPLOCATION_CREATE_FAILED =
  "API_V1_MAPLOCATION_CREATE_FAILED"
export const API_V1_MAPLOCATION_READ = "API_V1_MAPLOCATION_READ"
export const API_V1_MAPLOCATION_READ_SUCCEEDED =
  "API_V1_MAPLOCATION_READ_SUCCEEDED"
export const API_V1_MAPLOCATION_READ_FAILED = "API_V1_MAPLOCATION_READ_FAILED"
export const API_V1_MAPLOCATION_UPDATE = "API_V1_MAPLOCATION_UPDATE"
export const API_V1_MAPLOCATION_UPDATE_SUCCEEDED =
  "API_V1_MAPLOCATION_UPDATE_SUCCEEDED"
export const API_V1_MAPLOCATION_UPDATE_FAILED =
  "API_V1_MAPLOCATION_UPDATE_FAILED"
export const API_V1_MAPLOCATION_PARTIAL_UPDATE =
  "API_V1_MAPLOCATION_PARTIAL_UPDATE"
export const API_V1_MAPLOCATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_MAPLOCATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_MAPLOCATION_PARTIAL_UPDATE_FAILED =
  "API_V1_MAPLOCATION_PARTIAL_UPDATE_FAILED"
export const API_V1_MAPLOCATION_DELETE = "API_V1_MAPLOCATION_DELETE"
export const API_V1_MAPLOCATION_DELETE_SUCCEEDED =
  "API_V1_MAPLOCATION_DELETE_SUCCEEDED"
export const API_V1_MAPLOCATION_DELETE_FAILED =
  "API_V1_MAPLOCATION_DELETE_FAILED"
export const API_V1_MESSAGE_LIST = "API_V1_MESSAGE_LIST"
export const API_V1_MESSAGE_LIST_SUCCEEDED = "API_V1_MESSAGE_LIST_SUCCEEDED"
export const API_V1_MESSAGE_LIST_FAILED = "API_V1_MESSAGE_LIST_FAILED"
export const API_V1_MESSAGE_CREATE = "API_V1_MESSAGE_CREATE"
export const API_V1_MESSAGE_CREATE_SUCCEEDED = "API_V1_MESSAGE_CREATE_SUCCEEDED"
export const API_V1_MESSAGE_CREATE_FAILED = "API_V1_MESSAGE_CREATE_FAILED"
export const API_V1_MESSAGE_READ = "API_V1_MESSAGE_READ"
export const API_V1_MESSAGE_READ_SUCCEEDED = "API_V1_MESSAGE_READ_SUCCEEDED"
export const API_V1_MESSAGE_READ_FAILED = "API_V1_MESSAGE_READ_FAILED"
export const API_V1_MESSAGE_UPDATE = "API_V1_MESSAGE_UPDATE"
export const API_V1_MESSAGE_UPDATE_SUCCEEDED = "API_V1_MESSAGE_UPDATE_SUCCEEDED"
export const API_V1_MESSAGE_UPDATE_FAILED = "API_V1_MESSAGE_UPDATE_FAILED"
export const API_V1_MESSAGE_PARTIAL_UPDATE = "API_V1_MESSAGE_PARTIAL_UPDATE"
export const API_V1_MESSAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_MESSAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_MESSAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_MESSAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_MESSAGE_DELETE = "API_V1_MESSAGE_DELETE"
export const API_V1_MESSAGE_DELETE_SUCCEEDED = "API_V1_MESSAGE_DELETE_SUCCEEDED"
export const API_V1_MESSAGE_DELETE_FAILED = "API_V1_MESSAGE_DELETE_FAILED"
export const API_V1_NOTIFICATION_LIST = "API_V1_NOTIFICATION_LIST"
export const API_V1_NOTIFICATION_LIST_SUCCEEDED =
  "API_V1_NOTIFICATION_LIST_SUCCEEDED"
export const API_V1_NOTIFICATION_LIST_FAILED = "API_V1_NOTIFICATION_LIST_FAILED"
export const API_V1_NOTIFICATION_CREATE = "API_V1_NOTIFICATION_CREATE"
export const API_V1_NOTIFICATION_CREATE_SUCCEEDED =
  "API_V1_NOTIFICATION_CREATE_SUCCEEDED"
export const API_V1_NOTIFICATION_CREATE_FAILED =
  "API_V1_NOTIFICATION_CREATE_FAILED"
export const API_V1_NOTIFICATION_READ = "API_V1_NOTIFICATION_READ"
export const API_V1_NOTIFICATION_READ_SUCCEEDED =
  "API_V1_NOTIFICATION_READ_SUCCEEDED"
export const API_V1_NOTIFICATION_READ_FAILED = "API_V1_NOTIFICATION_READ_FAILED"
export const API_V1_NOTIFICATION_UPDATE = "API_V1_NOTIFICATION_UPDATE"
export const API_V1_NOTIFICATION_UPDATE_SUCCEEDED =
  "API_V1_NOTIFICATION_UPDATE_SUCCEEDED"
export const API_V1_NOTIFICATION_UPDATE_FAILED =
  "API_V1_NOTIFICATION_UPDATE_FAILED"
export const API_V1_NOTIFICATION_PARTIAL_UPDATE =
  "API_V1_NOTIFICATION_PARTIAL_UPDATE"
export const API_V1_NOTIFICATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_NOTIFICATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_NOTIFICATION_PARTIAL_UPDATE_FAILED =
  "API_V1_NOTIFICATION_PARTIAL_UPDATE_FAILED"
export const API_V1_NOTIFICATION_DELETE = "API_V1_NOTIFICATION_DELETE"
export const API_V1_NOTIFICATION_DELETE_SUCCEEDED =
  "API_V1_NOTIFICATION_DELETE_SUCCEEDED"
export const API_V1_NOTIFICATION_DELETE_FAILED =
  "API_V1_NOTIFICATION_DELETE_FAILED"
export const API_V1_PAYMENTMETHOD_LIST = "API_V1_PAYMENTMETHOD_LIST"
export const API_V1_PAYMENTMETHOD_LIST_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_LIST_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_LIST_FAILED =
  "API_V1_PAYMENTMETHOD_LIST_FAILED"
export const API_V1_PAYMENTMETHOD_CREATE = "API_V1_PAYMENTMETHOD_CREATE"
export const API_V1_PAYMENTMETHOD_CREATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_CREATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_CREATE_FAILED =
  "API_V1_PAYMENTMETHOD_CREATE_FAILED"
export const API_V1_PAYMENTMETHOD_READ = "API_V1_PAYMENTMETHOD_READ"
export const API_V1_PAYMENTMETHOD_READ_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_READ_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_READ_FAILED =
  "API_V1_PAYMENTMETHOD_READ_FAILED"
export const API_V1_PAYMENTMETHOD_UPDATE = "API_V1_PAYMENTMETHOD_UPDATE"
export const API_V1_PAYMENTMETHOD_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_UPDATE_FAILED =
  "API_V1_PAYMENTMETHOD_UPDATE_FAILED"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_FAILED =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_FAILED"
export const API_V1_PAYMENTMETHOD_DELETE = "API_V1_PAYMENTMETHOD_DELETE"
export const API_V1_PAYMENTMETHOD_DELETE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_DELETE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_DELETE_FAILED =
  "API_V1_PAYMENTMETHOD_DELETE_FAILED"
export const API_V1_PAYMENTTRANSACTION_LIST = "API_V1_PAYMENTTRANSACTION_LIST"
export const API_V1_PAYMENTTRANSACTION_LIST_SUCCEEDED =
  "API_V1_PAYMENTTRANSACTION_LIST_SUCCEEDED"
export const API_V1_PAYMENTTRANSACTION_LIST_FAILED =
  "API_V1_PAYMENTTRANSACTION_LIST_FAILED"
export const API_V1_PAYMENTTRANSACTION_CREATE =
  "API_V1_PAYMENTTRANSACTION_CREATE"
export const API_V1_PAYMENTTRANSACTION_CREATE_SUCCEEDED =
  "API_V1_PAYMENTTRANSACTION_CREATE_SUCCEEDED"
export const API_V1_PAYMENTTRANSACTION_CREATE_FAILED =
  "API_V1_PAYMENTTRANSACTION_CREATE_FAILED"
export const API_V1_PAYMENTTRANSACTION_READ = "API_V1_PAYMENTTRANSACTION_READ"
export const API_V1_PAYMENTTRANSACTION_READ_SUCCEEDED =
  "API_V1_PAYMENTTRANSACTION_READ_SUCCEEDED"
export const API_V1_PAYMENTTRANSACTION_READ_FAILED =
  "API_V1_PAYMENTTRANSACTION_READ_FAILED"
export const API_V1_PAYMENTTRANSACTION_UPDATE =
  "API_V1_PAYMENTTRANSACTION_UPDATE"
export const API_V1_PAYMENTTRANSACTION_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTTRANSACTION_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTTRANSACTION_UPDATE_FAILED =
  "API_V1_PAYMENTTRANSACTION_UPDATE_FAILED"
export const API_V1_PAYMENTTRANSACTION_PARTIAL_UPDATE =
  "API_V1_PAYMENTTRANSACTION_PARTIAL_UPDATE"
export const API_V1_PAYMENTTRANSACTION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTTRANSACTION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTTRANSACTION_PARTIAL_UPDATE_FAILED =
  "API_V1_PAYMENTTRANSACTION_PARTIAL_UPDATE_FAILED"
export const API_V1_PAYMENTTRANSACTION_DELETE =
  "API_V1_PAYMENTTRANSACTION_DELETE"
export const API_V1_PAYMENTTRANSACTION_DELETE_SUCCEEDED =
  "API_V1_PAYMENTTRANSACTION_DELETE_SUCCEEDED"
export const API_V1_PAYMENTTRANSACTION_DELETE_FAILED =
  "API_V1_PAYMENTTRANSACTION_DELETE_FAILED"
export const API_V1_RATING_LIST = "API_V1_RATING_LIST"
export const API_V1_RATING_LIST_SUCCEEDED = "API_V1_RATING_LIST_SUCCEEDED"
export const API_V1_RATING_LIST_FAILED = "API_V1_RATING_LIST_FAILED"
export const API_V1_RATING_CREATE = "API_V1_RATING_CREATE"
export const API_V1_RATING_CREATE_SUCCEEDED = "API_V1_RATING_CREATE_SUCCEEDED"
export const API_V1_RATING_CREATE_FAILED = "API_V1_RATING_CREATE_FAILED"
export const API_V1_RATING_READ = "API_V1_RATING_READ"
export const API_V1_RATING_READ_SUCCEEDED = "API_V1_RATING_READ_SUCCEEDED"
export const API_V1_RATING_READ_FAILED = "API_V1_RATING_READ_FAILED"
export const API_V1_RATING_UPDATE = "API_V1_RATING_UPDATE"
export const API_V1_RATING_UPDATE_SUCCEEDED = "API_V1_RATING_UPDATE_SUCCEEDED"
export const API_V1_RATING_UPDATE_FAILED = "API_V1_RATING_UPDATE_FAILED"
export const API_V1_RATING_PARTIAL_UPDATE = "API_V1_RATING_PARTIAL_UPDATE"
export const API_V1_RATING_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_RATING_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_RATING_PARTIAL_UPDATE_FAILED =
  "API_V1_RATING_PARTIAL_UPDATE_FAILED"
export const API_V1_RATING_DELETE = "API_V1_RATING_DELETE"
export const API_V1_RATING_DELETE_SUCCEEDED = "API_V1_RATING_DELETE_SUCCEEDED"
export const API_V1_RATING_DELETE_FAILED = "API_V1_RATING_DELETE_FAILED"
export const API_V1_SIGNUP_CREATE = "API_V1_SIGNUP_CREATE"
export const API_V1_SIGNUP_CREATE_SUCCEEDED = "API_V1_SIGNUP_CREATE_SUCCEEDED"
export const API_V1_SIGNUP_CREATE_FAILED = "API_V1_SIGNUP_CREATE_FAILED"
export const API_V1_SUBCATEGORY_LIST = "API_V1_SUBCATEGORY_LIST"
export const API_V1_SUBCATEGORY_LIST_SUCCEEDED =
  "API_V1_SUBCATEGORY_LIST_SUCCEEDED"
export const API_V1_SUBCATEGORY_LIST_FAILED = "API_V1_SUBCATEGORY_LIST_FAILED"
export const API_V1_SUBCATEGORY_CREATE = "API_V1_SUBCATEGORY_CREATE"
export const API_V1_SUBCATEGORY_CREATE_SUCCEEDED =
  "API_V1_SUBCATEGORY_CREATE_SUCCEEDED"
export const API_V1_SUBCATEGORY_CREATE_FAILED =
  "API_V1_SUBCATEGORY_CREATE_FAILED"
export const API_V1_SUBCATEGORY_READ = "API_V1_SUBCATEGORY_READ"
export const API_V1_SUBCATEGORY_READ_SUCCEEDED =
  "API_V1_SUBCATEGORY_READ_SUCCEEDED"
export const API_V1_SUBCATEGORY_READ_FAILED = "API_V1_SUBCATEGORY_READ_FAILED"
export const API_V1_SUBCATEGORY_UPDATE = "API_V1_SUBCATEGORY_UPDATE"
export const API_V1_SUBCATEGORY_UPDATE_SUCCEEDED =
  "API_V1_SUBCATEGORY_UPDATE_SUCCEEDED"
export const API_V1_SUBCATEGORY_UPDATE_FAILED =
  "API_V1_SUBCATEGORY_UPDATE_FAILED"
export const API_V1_SUBCATEGORY_PARTIAL_UPDATE =
  "API_V1_SUBCATEGORY_PARTIAL_UPDATE"
export const API_V1_SUBCATEGORY_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_SUBCATEGORY_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_SUBCATEGORY_PARTIAL_UPDATE_FAILED =
  "API_V1_SUBCATEGORY_PARTIAL_UPDATE_FAILED"
export const API_V1_SUBCATEGORY_DELETE = "API_V1_SUBCATEGORY_DELETE"
export const API_V1_SUBCATEGORY_DELETE_SUCCEEDED =
  "API_V1_SUBCATEGORY_DELETE_SUCCEEDED"
export const API_V1_SUBCATEGORY_DELETE_FAILED =
  "API_V1_SUBCATEGORY_DELETE_FAILED"
export const API_V1_TASK_LIST = "API_V1_TASK_LIST"
export const API_V1_TASK_LIST_SUCCEEDED = "API_V1_TASK_LIST_SUCCEEDED"
export const API_V1_TASK_LIST_FAILED = "API_V1_TASK_LIST_FAILED"
export const API_V1_TASK_CREATE = "API_V1_TASK_CREATE"
export const API_V1_TASK_CREATE_SUCCEEDED = "API_V1_TASK_CREATE_SUCCEEDED"
export const API_V1_TASK_CREATE_FAILED = "API_V1_TASK_CREATE_FAILED"
export const API_V1_TASK_READ = "API_V1_TASK_READ"
export const API_V1_TASK_READ_SUCCEEDED = "API_V1_TASK_READ_SUCCEEDED"
export const API_V1_TASK_READ_FAILED = "API_V1_TASK_READ_FAILED"
export const API_V1_TASK_UPDATE = "API_V1_TASK_UPDATE"
export const API_V1_TASK_UPDATE_SUCCEEDED = "API_V1_TASK_UPDATE_SUCCEEDED"
export const API_V1_TASK_UPDATE_FAILED = "API_V1_TASK_UPDATE_FAILED"
export const API_V1_TASK_PARTIAL_UPDATE = "API_V1_TASK_PARTIAL_UPDATE"
export const API_V1_TASK_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TASK_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TASK_PARTIAL_UPDATE_FAILED =
  "API_V1_TASK_PARTIAL_UPDATE_FAILED"
export const API_V1_TASK_DELETE = "API_V1_TASK_DELETE"
export const API_V1_TASK_DELETE_SUCCEEDED = "API_V1_TASK_DELETE_SUCCEEDED"
export const API_V1_TASK_DELETE_FAILED = "API_V1_TASK_DELETE_FAILED"
export const API_V1_TASKERAVAILABILITY_LIST = "API_V1_TASKERAVAILABILITY_LIST"
export const API_V1_TASKERAVAILABILITY_LIST_SUCCEEDED =
  "API_V1_TASKERAVAILABILITY_LIST_SUCCEEDED"
export const API_V1_TASKERAVAILABILITY_LIST_FAILED =
  "API_V1_TASKERAVAILABILITY_LIST_FAILED"
export const API_V1_TASKERAVAILABILITY_CREATE =
  "API_V1_TASKERAVAILABILITY_CREATE"
export const API_V1_TASKERAVAILABILITY_CREATE_SUCCEEDED =
  "API_V1_TASKERAVAILABILITY_CREATE_SUCCEEDED"
export const API_V1_TASKERAVAILABILITY_CREATE_FAILED =
  "API_V1_TASKERAVAILABILITY_CREATE_FAILED"
export const API_V1_TASKERAVAILABILITY_READ = "API_V1_TASKERAVAILABILITY_READ"
export const API_V1_TASKERAVAILABILITY_READ_SUCCEEDED =
  "API_V1_TASKERAVAILABILITY_READ_SUCCEEDED"
export const API_V1_TASKERAVAILABILITY_READ_FAILED =
  "API_V1_TASKERAVAILABILITY_READ_FAILED"
export const API_V1_TASKERAVAILABILITY_UPDATE =
  "API_V1_TASKERAVAILABILITY_UPDATE"
export const API_V1_TASKERAVAILABILITY_UPDATE_SUCCEEDED =
  "API_V1_TASKERAVAILABILITY_UPDATE_SUCCEEDED"
export const API_V1_TASKERAVAILABILITY_UPDATE_FAILED =
  "API_V1_TASKERAVAILABILITY_UPDATE_FAILED"
export const API_V1_TASKERAVAILABILITY_PARTIAL_UPDATE =
  "API_V1_TASKERAVAILABILITY_PARTIAL_UPDATE"
export const API_V1_TASKERAVAILABILITY_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TASKERAVAILABILITY_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TASKERAVAILABILITY_PARTIAL_UPDATE_FAILED =
  "API_V1_TASKERAVAILABILITY_PARTIAL_UPDATE_FAILED"
export const API_V1_TASKERAVAILABILITY_DELETE =
  "API_V1_TASKERAVAILABILITY_DELETE"
export const API_V1_TASKERAVAILABILITY_DELETE_SUCCEEDED =
  "API_V1_TASKERAVAILABILITY_DELETE_SUCCEEDED"
export const API_V1_TASKERAVAILABILITY_DELETE_FAILED =
  "API_V1_TASKERAVAILABILITY_DELETE_FAILED"
export const API_V1_TASKERLOCATION_LIST = "API_V1_TASKERLOCATION_LIST"
export const API_V1_TASKERLOCATION_LIST_SUCCEEDED =
  "API_V1_TASKERLOCATION_LIST_SUCCEEDED"
export const API_V1_TASKERLOCATION_LIST_FAILED =
  "API_V1_TASKERLOCATION_LIST_FAILED"
export const API_V1_TASKERLOCATION_CREATE = "API_V1_TASKERLOCATION_CREATE"
export const API_V1_TASKERLOCATION_CREATE_SUCCEEDED =
  "API_V1_TASKERLOCATION_CREATE_SUCCEEDED"
export const API_V1_TASKERLOCATION_CREATE_FAILED =
  "API_V1_TASKERLOCATION_CREATE_FAILED"
export const API_V1_TASKERLOCATION_READ = "API_V1_TASKERLOCATION_READ"
export const API_V1_TASKERLOCATION_READ_SUCCEEDED =
  "API_V1_TASKERLOCATION_READ_SUCCEEDED"
export const API_V1_TASKERLOCATION_READ_FAILED =
  "API_V1_TASKERLOCATION_READ_FAILED"
export const API_V1_TASKERLOCATION_UPDATE = "API_V1_TASKERLOCATION_UPDATE"
export const API_V1_TASKERLOCATION_UPDATE_SUCCEEDED =
  "API_V1_TASKERLOCATION_UPDATE_SUCCEEDED"
export const API_V1_TASKERLOCATION_UPDATE_FAILED =
  "API_V1_TASKERLOCATION_UPDATE_FAILED"
export const API_V1_TASKERLOCATION_PARTIAL_UPDATE =
  "API_V1_TASKERLOCATION_PARTIAL_UPDATE"
export const API_V1_TASKERLOCATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TASKERLOCATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TASKERLOCATION_PARTIAL_UPDATE_FAILED =
  "API_V1_TASKERLOCATION_PARTIAL_UPDATE_FAILED"
export const API_V1_TASKERLOCATION_DELETE = "API_V1_TASKERLOCATION_DELETE"
export const API_V1_TASKERLOCATION_DELETE_SUCCEEDED =
  "API_V1_TASKERLOCATION_DELETE_SUCCEEDED"
export const API_V1_TASKERLOCATION_DELETE_FAILED =
  "API_V1_TASKERLOCATION_DELETE_FAILED"
export const API_V1_TASKERPAYMENTACCOUNT_LIST =
  "API_V1_TASKERPAYMENTACCOUNT_LIST"
export const API_V1_TASKERPAYMENTACCOUNT_LIST_SUCCEEDED =
  "API_V1_TASKERPAYMENTACCOUNT_LIST_SUCCEEDED"
export const API_V1_TASKERPAYMENTACCOUNT_LIST_FAILED =
  "API_V1_TASKERPAYMENTACCOUNT_LIST_FAILED"
export const API_V1_TASKERPAYMENTACCOUNT_CREATE =
  "API_V1_TASKERPAYMENTACCOUNT_CREATE"
export const API_V1_TASKERPAYMENTACCOUNT_CREATE_SUCCEEDED =
  "API_V1_TASKERPAYMENTACCOUNT_CREATE_SUCCEEDED"
export const API_V1_TASKERPAYMENTACCOUNT_CREATE_FAILED =
  "API_V1_TASKERPAYMENTACCOUNT_CREATE_FAILED"
export const API_V1_TASKERPAYMENTACCOUNT_READ =
  "API_V1_TASKERPAYMENTACCOUNT_READ"
export const API_V1_TASKERPAYMENTACCOUNT_READ_SUCCEEDED =
  "API_V1_TASKERPAYMENTACCOUNT_READ_SUCCEEDED"
export const API_V1_TASKERPAYMENTACCOUNT_READ_FAILED =
  "API_V1_TASKERPAYMENTACCOUNT_READ_FAILED"
export const API_V1_TASKERPAYMENTACCOUNT_UPDATE =
  "API_V1_TASKERPAYMENTACCOUNT_UPDATE"
export const API_V1_TASKERPAYMENTACCOUNT_UPDATE_SUCCEEDED =
  "API_V1_TASKERPAYMENTACCOUNT_UPDATE_SUCCEEDED"
export const API_V1_TASKERPAYMENTACCOUNT_UPDATE_FAILED =
  "API_V1_TASKERPAYMENTACCOUNT_UPDATE_FAILED"
export const API_V1_TASKERPAYMENTACCOUNT_PARTIAL_UPDATE =
  "API_V1_TASKERPAYMENTACCOUNT_PARTIAL_UPDATE"
export const API_V1_TASKERPAYMENTACCOUNT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TASKERPAYMENTACCOUNT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TASKERPAYMENTACCOUNT_PARTIAL_UPDATE_FAILED =
  "API_V1_TASKERPAYMENTACCOUNT_PARTIAL_UPDATE_FAILED"
export const API_V1_TASKERPAYMENTACCOUNT_DELETE =
  "API_V1_TASKERPAYMENTACCOUNT_DELETE"
export const API_V1_TASKERPAYMENTACCOUNT_DELETE_SUCCEEDED =
  "API_V1_TASKERPAYMENTACCOUNT_DELETE_SUCCEEDED"
export const API_V1_TASKERPAYMENTACCOUNT_DELETE_FAILED =
  "API_V1_TASKERPAYMENTACCOUNT_DELETE_FAILED"
export const API_V1_TASKERPROFILE_LIST = "API_V1_TASKERPROFILE_LIST"
export const API_V1_TASKERPROFILE_LIST_SUCCEEDED =
  "API_V1_TASKERPROFILE_LIST_SUCCEEDED"
export const API_V1_TASKERPROFILE_LIST_FAILED =
  "API_V1_TASKERPROFILE_LIST_FAILED"
export const API_V1_TASKERPROFILE_CREATE = "API_V1_TASKERPROFILE_CREATE"
export const API_V1_TASKERPROFILE_CREATE_SUCCEEDED =
  "API_V1_TASKERPROFILE_CREATE_SUCCEEDED"
export const API_V1_TASKERPROFILE_CREATE_FAILED =
  "API_V1_TASKERPROFILE_CREATE_FAILED"
export const API_V1_TASKERPROFILE_READ = "API_V1_TASKERPROFILE_READ"
export const API_V1_TASKERPROFILE_READ_SUCCEEDED =
  "API_V1_TASKERPROFILE_READ_SUCCEEDED"
export const API_V1_TASKERPROFILE_READ_FAILED =
  "API_V1_TASKERPROFILE_READ_FAILED"
export const API_V1_TASKERPROFILE_UPDATE = "API_V1_TASKERPROFILE_UPDATE"
export const API_V1_TASKERPROFILE_UPDATE_SUCCEEDED =
  "API_V1_TASKERPROFILE_UPDATE_SUCCEEDED"
export const API_V1_TASKERPROFILE_UPDATE_FAILED =
  "API_V1_TASKERPROFILE_UPDATE_FAILED"
export const API_V1_TASKERPROFILE_PARTIAL_UPDATE =
  "API_V1_TASKERPROFILE_PARTIAL_UPDATE"
export const API_V1_TASKERPROFILE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TASKERPROFILE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TASKERPROFILE_PARTIAL_UPDATE_FAILED =
  "API_V1_TASKERPROFILE_PARTIAL_UPDATE_FAILED"
export const API_V1_TASKERPROFILE_DELETE = "API_V1_TASKERPROFILE_DELETE"
export const API_V1_TASKERPROFILE_DELETE_SUCCEEDED =
  "API_V1_TASKERPROFILE_DELETE_SUCCEEDED"
export const API_V1_TASKERPROFILE_DELETE_FAILED =
  "API_V1_TASKERPROFILE_DELETE_FAILED"
export const API_V1_TASKERSKILL_LIST = "API_V1_TASKERSKILL_LIST"
export const API_V1_TASKERSKILL_LIST_SUCCEEDED =
  "API_V1_TASKERSKILL_LIST_SUCCEEDED"
export const API_V1_TASKERSKILL_LIST_FAILED = "API_V1_TASKERSKILL_LIST_FAILED"
export const API_V1_TASKERSKILL_CREATE = "API_V1_TASKERSKILL_CREATE"
export const API_V1_TASKERSKILL_CREATE_SUCCEEDED =
  "API_V1_TASKERSKILL_CREATE_SUCCEEDED"
export const API_V1_TASKERSKILL_CREATE_FAILED =
  "API_V1_TASKERSKILL_CREATE_FAILED"
export const API_V1_TASKERSKILL_READ = "API_V1_TASKERSKILL_READ"
export const API_V1_TASKERSKILL_READ_SUCCEEDED =
  "API_V1_TASKERSKILL_READ_SUCCEEDED"
export const API_V1_TASKERSKILL_READ_FAILED = "API_V1_TASKERSKILL_READ_FAILED"
export const API_V1_TASKERSKILL_UPDATE = "API_V1_TASKERSKILL_UPDATE"
export const API_V1_TASKERSKILL_UPDATE_SUCCEEDED =
  "API_V1_TASKERSKILL_UPDATE_SUCCEEDED"
export const API_V1_TASKERSKILL_UPDATE_FAILED =
  "API_V1_TASKERSKILL_UPDATE_FAILED"
export const API_V1_TASKERSKILL_PARTIAL_UPDATE =
  "API_V1_TASKERSKILL_PARTIAL_UPDATE"
export const API_V1_TASKERSKILL_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TASKERSKILL_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TASKERSKILL_PARTIAL_UPDATE_FAILED =
  "API_V1_TASKERSKILL_PARTIAL_UPDATE_FAILED"
export const API_V1_TASKERSKILL_DELETE = "API_V1_TASKERSKILL_DELETE"
export const API_V1_TASKERSKILL_DELETE_SUCCEEDED =
  "API_V1_TASKERSKILL_DELETE_SUCCEEDED"
export const API_V1_TASKERSKILL_DELETE_FAILED =
  "API_V1_TASKERSKILL_DELETE_FAILED"
export const API_V1_TASKERWALLET_LIST = "API_V1_TASKERWALLET_LIST"
export const API_V1_TASKERWALLET_LIST_SUCCEEDED =
  "API_V1_TASKERWALLET_LIST_SUCCEEDED"
export const API_V1_TASKERWALLET_LIST_FAILED = "API_V1_TASKERWALLET_LIST_FAILED"
export const API_V1_TASKERWALLET_CREATE = "API_V1_TASKERWALLET_CREATE"
export const API_V1_TASKERWALLET_CREATE_SUCCEEDED =
  "API_V1_TASKERWALLET_CREATE_SUCCEEDED"
export const API_V1_TASKERWALLET_CREATE_FAILED =
  "API_V1_TASKERWALLET_CREATE_FAILED"
export const API_V1_TASKERWALLET_READ = "API_V1_TASKERWALLET_READ"
export const API_V1_TASKERWALLET_READ_SUCCEEDED =
  "API_V1_TASKERWALLET_READ_SUCCEEDED"
export const API_V1_TASKERWALLET_READ_FAILED = "API_V1_TASKERWALLET_READ_FAILED"
export const API_V1_TASKERWALLET_UPDATE = "API_V1_TASKERWALLET_UPDATE"
export const API_V1_TASKERWALLET_UPDATE_SUCCEEDED =
  "API_V1_TASKERWALLET_UPDATE_SUCCEEDED"
export const API_V1_TASKERWALLET_UPDATE_FAILED =
  "API_V1_TASKERWALLET_UPDATE_FAILED"
export const API_V1_TASKERWALLET_PARTIAL_UPDATE =
  "API_V1_TASKERWALLET_PARTIAL_UPDATE"
export const API_V1_TASKERWALLET_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TASKERWALLET_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TASKERWALLET_PARTIAL_UPDATE_FAILED =
  "API_V1_TASKERWALLET_PARTIAL_UPDATE_FAILED"
export const API_V1_TASKERWALLET_DELETE = "API_V1_TASKERWALLET_DELETE"
export const API_V1_TASKERWALLET_DELETE_SUCCEEDED =
  "API_V1_TASKERWALLET_DELETE_SUCCEEDED"
export const API_V1_TASKERWALLET_DELETE_FAILED =
  "API_V1_TASKERWALLET_DELETE_FAILED"
export const API_V1_TASKLOCATION_LIST = "API_V1_TASKLOCATION_LIST"
export const API_V1_TASKLOCATION_LIST_SUCCEEDED =
  "API_V1_TASKLOCATION_LIST_SUCCEEDED"
export const API_V1_TASKLOCATION_LIST_FAILED = "API_V1_TASKLOCATION_LIST_FAILED"
export const API_V1_TASKLOCATION_CREATE = "API_V1_TASKLOCATION_CREATE"
export const API_V1_TASKLOCATION_CREATE_SUCCEEDED =
  "API_V1_TASKLOCATION_CREATE_SUCCEEDED"
export const API_V1_TASKLOCATION_CREATE_FAILED =
  "API_V1_TASKLOCATION_CREATE_FAILED"
export const API_V1_TASKLOCATION_READ = "API_V1_TASKLOCATION_READ"
export const API_V1_TASKLOCATION_READ_SUCCEEDED =
  "API_V1_TASKLOCATION_READ_SUCCEEDED"
export const API_V1_TASKLOCATION_READ_FAILED = "API_V1_TASKLOCATION_READ_FAILED"
export const API_V1_TASKLOCATION_UPDATE = "API_V1_TASKLOCATION_UPDATE"
export const API_V1_TASKLOCATION_UPDATE_SUCCEEDED =
  "API_V1_TASKLOCATION_UPDATE_SUCCEEDED"
export const API_V1_TASKLOCATION_UPDATE_FAILED =
  "API_V1_TASKLOCATION_UPDATE_FAILED"
export const API_V1_TASKLOCATION_PARTIAL_UPDATE =
  "API_V1_TASKLOCATION_PARTIAL_UPDATE"
export const API_V1_TASKLOCATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TASKLOCATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TASKLOCATION_PARTIAL_UPDATE_FAILED =
  "API_V1_TASKLOCATION_PARTIAL_UPDATE_FAILED"
export const API_V1_TASKLOCATION_DELETE = "API_V1_TASKLOCATION_DELETE"
export const API_V1_TASKLOCATION_DELETE_SUCCEEDED =
  "API_V1_TASKLOCATION_DELETE_SUCCEEDED"
export const API_V1_TASKLOCATION_DELETE_FAILED =
  "API_V1_TASKLOCATION_DELETE_FAILED"
export const API_V1_TASKTRANSACTION_LIST = "API_V1_TASKTRANSACTION_LIST"
export const API_V1_TASKTRANSACTION_LIST_SUCCEEDED =
  "API_V1_TASKTRANSACTION_LIST_SUCCEEDED"
export const API_V1_TASKTRANSACTION_LIST_FAILED =
  "API_V1_TASKTRANSACTION_LIST_FAILED"
export const API_V1_TASKTRANSACTION_CREATE = "API_V1_TASKTRANSACTION_CREATE"
export const API_V1_TASKTRANSACTION_CREATE_SUCCEEDED =
  "API_V1_TASKTRANSACTION_CREATE_SUCCEEDED"
export const API_V1_TASKTRANSACTION_CREATE_FAILED =
  "API_V1_TASKTRANSACTION_CREATE_FAILED"
export const API_V1_TASKTRANSACTION_READ = "API_V1_TASKTRANSACTION_READ"
export const API_V1_TASKTRANSACTION_READ_SUCCEEDED =
  "API_V1_TASKTRANSACTION_READ_SUCCEEDED"
export const API_V1_TASKTRANSACTION_READ_FAILED =
  "API_V1_TASKTRANSACTION_READ_FAILED"
export const API_V1_TASKTRANSACTION_UPDATE = "API_V1_TASKTRANSACTION_UPDATE"
export const API_V1_TASKTRANSACTION_UPDATE_SUCCEEDED =
  "API_V1_TASKTRANSACTION_UPDATE_SUCCEEDED"
export const API_V1_TASKTRANSACTION_UPDATE_FAILED =
  "API_V1_TASKTRANSACTION_UPDATE_FAILED"
export const API_V1_TASKTRANSACTION_PARTIAL_UPDATE =
  "API_V1_TASKTRANSACTION_PARTIAL_UPDATE"
export const API_V1_TASKTRANSACTION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TASKTRANSACTION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TASKTRANSACTION_PARTIAL_UPDATE_FAILED =
  "API_V1_TASKTRANSACTION_PARTIAL_UPDATE_FAILED"
export const API_V1_TASKTRANSACTION_DELETE = "API_V1_TASKTRANSACTION_DELETE"
export const API_V1_TASKTRANSACTION_DELETE_SUCCEEDED =
  "API_V1_TASKTRANSACTION_DELETE_SUCCEEDED"
export const API_V1_TASKTRANSACTION_DELETE_FAILED =
  "API_V1_TASKTRANSACTION_DELETE_FAILED"
export const API_V1_TIMESLOT_LIST = "API_V1_TIMESLOT_LIST"
export const API_V1_TIMESLOT_LIST_SUCCEEDED = "API_V1_TIMESLOT_LIST_SUCCEEDED"
export const API_V1_TIMESLOT_LIST_FAILED = "API_V1_TIMESLOT_LIST_FAILED"
export const API_V1_TIMESLOT_CREATE = "API_V1_TIMESLOT_CREATE"
export const API_V1_TIMESLOT_CREATE_SUCCEEDED =
  "API_V1_TIMESLOT_CREATE_SUCCEEDED"
export const API_V1_TIMESLOT_CREATE_FAILED = "API_V1_TIMESLOT_CREATE_FAILED"
export const API_V1_TIMESLOT_READ = "API_V1_TIMESLOT_READ"
export const API_V1_TIMESLOT_READ_SUCCEEDED = "API_V1_TIMESLOT_READ_SUCCEEDED"
export const API_V1_TIMESLOT_READ_FAILED = "API_V1_TIMESLOT_READ_FAILED"
export const API_V1_TIMESLOT_UPDATE = "API_V1_TIMESLOT_UPDATE"
export const API_V1_TIMESLOT_UPDATE_SUCCEEDED =
  "API_V1_TIMESLOT_UPDATE_SUCCEEDED"
export const API_V1_TIMESLOT_UPDATE_FAILED = "API_V1_TIMESLOT_UPDATE_FAILED"
export const API_V1_TIMESLOT_PARTIAL_UPDATE = "API_V1_TIMESLOT_PARTIAL_UPDATE"
export const API_V1_TIMESLOT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_TIMESLOT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_TIMESLOT_PARTIAL_UPDATE_FAILED =
  "API_V1_TIMESLOT_PARTIAL_UPDATE_FAILED"
export const API_V1_TIMESLOT_DELETE = "API_V1_TIMESLOT_DELETE"
export const API_V1_TIMESLOT_DELETE_SUCCEEDED =
  "API_V1_TIMESLOT_DELETE_SUCCEEDED"
export const API_V1_TIMESLOT_DELETE_FAILED = "API_V1_TIMESLOT_DELETE_FAILED"
export const REST_AUTH_LOGIN_CREATE = "REST_AUTH_LOGIN_CREATE"
export const REST_AUTH_LOGIN_CREATE_SUCCEEDED =
  "REST_AUTH_LOGIN_CREATE_SUCCEEDED"
export const REST_AUTH_LOGIN_CREATE_FAILED = "REST_AUTH_LOGIN_CREATE_FAILED"
export const REST_AUTH_LOGOUT_LIST = "REST_AUTH_LOGOUT_LIST"
export const REST_AUTH_LOGOUT_LIST_SUCCEEDED = "REST_AUTH_LOGOUT_LIST_SUCCEEDED"
export const REST_AUTH_LOGOUT_LIST_FAILED = "REST_AUTH_LOGOUT_LIST_FAILED"
export const REST_AUTH_LOGOUT_CREATE = "REST_AUTH_LOGOUT_CREATE"
export const REST_AUTH_LOGOUT_CREATE_SUCCEEDED =
  "REST_AUTH_LOGOUT_CREATE_SUCCEEDED"
export const REST_AUTH_LOGOUT_CREATE_FAILED = "REST_AUTH_LOGOUT_CREATE_FAILED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE =
  "REST_AUTH_PASSWORD_CHANGE_CREATE"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CREATE = "REST_AUTH_PASSWORD_RESET_CREATE"
export const REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_CREATE = "REST_AUTH_REGISTRATION_CREATE"
export const REST_AUTH_REGISTRATION_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED"
export const REST_AUTH_USER_READ = "REST_AUTH_USER_READ"
export const REST_AUTH_USER_READ_SUCCEEDED = "REST_AUTH_USER_READ_SUCCEEDED"
export const REST_AUTH_USER_READ_FAILED = "REST_AUTH_USER_READ_FAILED"
export const REST_AUTH_USER_UPDATE = "REST_AUTH_USER_UPDATE"
export const REST_AUTH_USER_UPDATE_SUCCEEDED = "REST_AUTH_USER_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_UPDATE_FAILED = "REST_AUTH_USER_UPDATE_FAILED"
export const REST_AUTH_USER_PARTIAL_UPDATE = "REST_AUTH_USER_PARTIAL_UPDATE"
export const REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED =
  "REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_PARTIAL_UPDATE_FAILED =
  "REST_AUTH_USER_PARTIAL_UPDATE_FAILED"
